easy_admin:
  site_name: "EURUS"
  entities:
    Generator:
     class:  App\Entity\Generator
     list:
       fields:
         - 'title'
         - 'power'
         - 'voltage'
         - 'type_generator'
     form:
       fields:
         - "title"
         - "power"
         - "type_generator"

    Projects:
     class:  App\Entity\Projects
     list:
       fields:
         - 'place'
         - 'date'
         - 'picture'
         - 'generators'
    User:
     class: App\Entity\User
     list:
       fields:
        - 'email'

    Service:
      class: App\Entity\Service
      list:
        fields:
         - 'title'
         - 'discription'
         - 'price'

    News:
      class: App\Entity\News
      list:
       fields:
         - 'title'
         - 'discription'
         - 'date'

