easy_admin:
<<<<<<< HEAD
  site_name: "EURUS"
  entities:
    Generator:
     class:  App\Entity\Generator
     list:
       fields:
         - 'title'
         - 'power'
         - 'voltage'
         - 'type_generator'
         - { property: 'image', type: 'image', base_path: "/assets/img/" }
       form:
         fields:
          - {property: "image", type: "file", label: "image_for_upload"}
          - "title"
          - "power"
          - "voltage"
          - "type_generator"
=======
  site_name: 'EURUS'
  entities:
        # change the following to the namespaces of your own entities
      add_generator:
        class: App\Entity\WindGenerator
      projects:
        class: App\Entity\Projects

>>>>>>> 0a2e7f4f2c56b7bb40cfb412d429b3e74e48ed85
